/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Amatsukast (https://sketchfab.com/Amatsukast)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/bow-and-arrow-1ce33880149543f9ae7b5848e6e52d66
Title: Bow and Arrow
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export const Archer = (props) => {
  const { nodes, materials } = useGLTF('/bow_and_arrow.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.05}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={1}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.arrow_arrow_mt_0.geometry}
              material={materials.arrow_mt}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.arrow_wing_mt_0.geometry}
              material={materials.wing_mt}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={1}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.bow_bow_wood_mt_0.geometry}
              material={materials.bow_wood_mt}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.bow_bow_metal_mt_0.geometry}
              material={materials.bow_metal_mt}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={1}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.arrow001_arrow_mt_0.geometry}
              material={materials.arrow_mt}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.arrow001_wing_mt_0.geometry}
              material={materials.wing_mt}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={1}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.arrow002_arrow_mt_0.geometry}
              material={materials.arrow_mt}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.arrow002_wing_mt_0.geometry}
              material={materials.wing_mt}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={1}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.arrow003_arrow_mt_0.geometry}
              material={materials.arrow_mt}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.arrow003_wing_mt_0.geometry}
              material={materials.wing_mt}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={1}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.arrow004_arrow_mt_0.geometry}
              material={materials.arrow_mt}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.arrow004_wing_mt_0.geometry}
              material={materials.wing_mt}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={1}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.arrow005_arrow_mt_0.geometry}
              material={materials.arrow_mt}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.arrow005_wing_mt_0.geometry}
              material={materials.wing_mt}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.quiver_quiver_mt_0.geometry}
            material={materials.quiver_mt}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/bow_and_arrow.glb');
