/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export const Floor = (props) => {
  const { nodes, materials } = useGLTF("/floor.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.environment.geometry}
        material={materials.Material}
      />
      <mesh geometry={nodes.NavMesh.geometry} material={materials.Material} />
    </group>
  );
};

useGLTF.preload("/floor.glb");
