/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export const Target = ({targetRef}) => {
  const { nodes, materials } = useGLTF("/target.glb");
  return (
    <group dispose={null}>
      <mesh
        ref={targetRef}
        castShadow
        geometry={nodes.target.geometry}
        material={materials["target.001"]}
        position={[0, 0.5, 0]}
        rotation={[1.309, 0, 0]}
      />
      <mesh
        castShadow
        geometry={nodes.frame.geometry}
        material={materials.wood}
        position={[0, 0.5, -0.499]}
        rotation={[0.262, 0, 0]}
        scale={[1, 0.891, 1]}
      />
    </group>
  );
};

useGLTF.preload("/target.glb");
