/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 track.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { DoubleSide } from "three";

export const Track = (props) => {
  const { nodes, materials } = useGLTF("/track.glb");

  Object.values(nodes).forEach((node) => {
    if (node.isMesh) {
      node.material.side = DoubleSide;
    }
  });

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Track.geometry}
        material={nodes.Track.material}
        ref={props.track}
      />
    </group>
  );
};

useGLTF.preload("/track.glb");
