/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export const EnvironmentFloor = (props) => {
  const { nodes, materials } = useGLTF("/environment.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.environment.geometry}
        material={materials.Material}
      />
    </group>
  );
};

useGLTF.preload("/environment.glb");
